
//default language is english
let lang = 'en';
const selector = document.querySelector('#lang');
selector.addEventListener('change', changeLang);
// taking the language selector and assign changing event
// the function for making change in language selector

function changeLang() {
    if (this.value === 'en') {
        lang = 'en';
    } else if (this.value === 'sw') {
        lang = 'sw';
    } else if (this.value === 'gm') {
        lang = 'gm';
    }
    // loading the content of the page

    display();
}
// taking the lists of keys and replace with the coresponding content stored in the dictionary

function display() {
    let keys = dict_OpenMenu.keys;
    for (let key of keys) {
        document.querySelector(`#${key}`).textContent = dict_OpenMenu[lang][key];
    }
    // taking the lists of attribute 

    let container = "";
    document.getElementById("itemsContainer").innerHTML = "";
    // $(document).ready(function () {
    var count = [{
        "nr": "10001",
        "articleid": "25053",
        "articletype": "100",
        "name": "Braastad XO",
        "name2": "",
        "priceinclvat": "442.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2000-08-07",
        "finaldelivery": " ",
        "catgegory": "Cognac",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Cognac, Fine Champagne",
        "countryoforiginlandname": "Frankrike",
        "producer": "Tiffon",
        "provider": "Arcus Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1001",
        "articleid": "190719",
        "articletype": "10",
        "name": "Vanlig Vodka",
        "name2": "",
        "priceinclvat": "195.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2006-04-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Svensk Export Vodka AB",
        "provider": "Fondberg",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1001201",
        "articleid": "51029",
        "articletype": "10012",
        "name": "Dworek Vodka",
        "name2": "",
        "priceinclvat": "190.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2004-12-06",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Polen",
        "producer": "Tarpan Fabryka Likierow",
        "provider": "TIWA Trading AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1001202",
        "articleid": "407506",
        "articletype": "10012",
        "name": "Dworek Vodka",
        "name2": "",
        "priceinclvat": "100.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2009-10-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Polen",
        "producer": "Tarpan Fabryka Likierow",
        "provider": "TIWA Trading AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1003802",
        "articleid": "513291",
        "articletype": "10038",
        "name": "Esping Jul B\u00c3\u00a4sk",
        "name2": "",
        "priceinclvat": "195.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2010-11-15",
        "finaldelivery": " ",
        "catgegory": "Kryddad sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Symposion International",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "32%",
        "module": "",
        "assortment": "TSS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1004703",
        "articleid": "723841",
        "articletype": "10047",
        "name": "Nils Oscar",
        "name2": "Celebration Ale",
        "priceinclvat": "43.70",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-02-01",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Ale",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Nils Oscar Company",
        "provider": "The Nils Oscar Company AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "9.4%",
        "module": "T5",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1004801",
        "articleid": "733051",
        "articletype": "10048",
        "name": "Rhum J. M",
        "name2": "",
        "priceinclvat": "729.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "Rom, M\u00c3\u00b6rk",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Martinique",
        "countryoforiginlandname": "Frankrike",
        "producer": "Les Heritiers Crassous de Mede",
        "provider": "Cask Sweden AB",
        "productionyear": "2001",
        "testedproductionyear": "",
        "alcoholstrength": "46.6%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1004901",
        "articleid": "733068",
        "articletype": "10049",
        "name": "Rhum J.M",
        "name2": "",
        "priceinclvat": "1399.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Rom, M\u00c3\u00b6rk",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Martinique",
        "countryoforiginlandname": "Frankrike",
        "producer": "Les Heritiers Crassous de Mede",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "44.8%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1005001",
        "articleid": "733084",
        "articletype": "10050",
        "name": "Balcones Texas",
        "name2": "",
        "priceinclvat": "899.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "USA",
        "producer": "Balcones Distilling",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "52.2%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1005101",
        "articleid": "733200",
        "articletype": "10051",
        "name": "Balcones Brimstone",
        "name2": "",
        "priceinclvat": "899.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, \u00c3\u2013vrig",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "USA",
        "producer": "Balcones Distilling",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "53.2%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1005201",
        "articleid": "733236",
        "articletype": "10052",
        "name": "Balcones True Blue",
        "name2": "",
        "priceinclvat": "899.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, \u00c3\u2013vrig",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "USA",
        "producer": "Balcones Distilling",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "50.2%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1005401",
        "articleid": "733429",
        "articletype": "10054",
        "name": "Linkwood",
        "name2": "the Octave",
        "priceinclvat": "1159.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Duncan Taylor Scotch Whisky",
        "provider": "Clydesdale AB",
        "productionyear": "1989",
        "testedproductionyear": "",
        "alcoholstrength": "51.7%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1005502",
        "articleid": "733446",
        "articletype": "10055",
        "name": "Marolo",
        "name2": "Grappa di Arneis Vigneto Renesio",
        "priceinclvat": "481.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Distilleria St Teresa dei Frat",
        "provider": "Haugen-Gruppen AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "50%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1005602",
        "articleid": "733468",
        "articletype": "10056",
        "name": "Cl\u00c3\u00a9ment",
        "name2": "Single Cask",
        "priceinclvat": "529.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Rom, M\u00c3\u00b6rk",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Martinique",
        "countryoforiginlandname": "Frankrike",
        "producer": "Les Heritiers Crassous de Mede",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "47.6%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "101",
        "articleid": "1",
        "articletype": "1",
        "name": "Renat",
        "name2": "",
        "priceinclvat": "203.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "1993-10-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Internationellt m\u00c3\u00a4rke",
        "producer": "Pernod Ricard",
        "provider": "Pernod Ricard Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1010001",
        "articleid": "817007",
        "articletype": "10100",
        "name": "Romano Levi",
        "name2": "Mostaco d\u00c2\u00b4Asti Donna Selvatica",
        "priceinclvat": "790.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-04-01",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Distilleria Levi Serafino ( di",
        "provider": "Haugen-Gruppen AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1010404",
        "articleid": "611864",
        "articletype": "10104",
        "name": "Giare 5 Grappe",
        "name2": "Moscato, Amarone, Teroldego, Chardonnay, Prosecco",
        "priceinclvat": "399.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-03-01",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "5 flaskor \u00c3\u00a0 100 ml",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Marzadro",
        "provider": "Stragas-Gruppen AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TST",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1010501",
        "articleid": "659534",
        "articletype": "10105",
        "name": "Genuin 25",
        "name2": "",
        "priceinclvat": "149.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-09-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Svensk Vodka i Motala AB",
        "provider": "Svensk Vodka i Motala AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "25%",
        "module": "",
        "assortment": "TST",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1011302",
        "articleid": "723428",
        "articletype": "10113",
        "name": "Kullados",
        "name2": "",
        "priceinclvat": "499.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013vrig sprit",
        "packaging": "Flaska",
        "captype": "Plastkork\/syntetkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Kullabygdens Musteri AB",
        "provider": "Kullabygdens Destilleri AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "T5",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1011401",
        "articleid": "811782",
        "articletype": "10114",
        "name": "Grappa Riserva Levi Romano",
        "name2": "Distilleria Levi Serafino Donna Selvatica",
        "priceinclvat": "989.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-03-01",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Distilleria Levi Serafino ( di",
        "provider": "Haugen-Gruppen AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "50%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1011601",
        "articleid": "614078",
        "articletype": "10116",
        "name": "Glenmorangie",
        "name2": "Pride",
        "priceinclvat": "24500.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-02-23",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Skottland, Highlands, Northern Highlands",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Glenmorangie",
        "provider": "Mo\u00c3\u00abt Hennessy Sverige AB",
        "productionyear": "1981",
        "testedproductionyear": "",
        "alcoholstrength": "56.7%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1011701",
        "articleid": "734763",
        "articletype": "10117",
        "name": "The Arran Malt",
        "name2": "Orkney Bere",
        "priceinclvat": "579.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands, Islands, Arran",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Isle of Arran Distillers",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1011901",
        "articleid": "614800",
        "articletype": "10119",
        "name": "Glen Garioch",
        "name2": "Mackillop's Choice",
        "priceinclvat": "895.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-02-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Angus Dundee",
        "provider": "Philipson S\u00c3\u00b6derberg AB",
        "productionyear": "1990",
        "testedproductionyear": "",
        "alcoholstrength": "43%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1012601",
        "articleid": "874805",
        "articletype": "10126",
        "name": "Nikka Taketsuru",
        "name2": "Pure Malt",
        "priceinclvat": "549.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-10-03",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Japan",
        "producer": "The Nikka Whisky Distilling Co",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "43%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1013104",
        "articleid": "734572",
        "articletype": "10131",
        "name": "Poli Grappa Barrel Pack",
        "name2": "",
        "priceinclvat": "549.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "5 flaskor \u00c3\u00a0 100 ml",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Distillerie Poli",
        "provider": "Bibendum",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1013201",
        "articleid": "633539",
        "articletype": "10132",
        "name": "Linkwood",
        "name2": "Duthies 23 Years",
        "priceinclvat": "950.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky , Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "William Cadenhead",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1013901",
        "articleid": "871188",
        "articletype": "10139",
        "name": "Longmorn",
        "name2": "16 Years",
        "priceinclvat": "1095.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-10-03",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Sansibar Whisky",
        "provider": "Symposion International AB",
        "productionyear": "1997",
        "testedproductionyear": "",
        "alcoholstrength": "48.5%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1014002",
        "articleid": "634582",
        "articletype": "10140",
        "name": "Braunstein",
        "name2": "Library Collection 11:1",
        "priceinclvat": "999.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Danmark",
        "producer": "Bryghuset Braunstein",
        "provider": "Galatea Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1014301",
        "articleid": "734788",
        "articletype": "10143",
        "name": "Waqar Pisco",
        "name2": "",
        "priceinclvat": "449.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Brandy och Vinsprit, Vinsprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Chile",
        "producer": "Tulahu\u00c3\u00a9n",
        "provider": "N57 Nordic AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1014804",
        "articleid": "638540",
        "articletype": "10148",
        "name": "Esprit Calvados 5 domaines",
        "name2": "",
        "priceinclvat": "695.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Calvados",
        "packaging": "5 flaskor \u00c3\u00a0 100 ml",
        "captype": "",
        "countryoforigin": "Normandie, Calvados, Calvados du Pays d'",
        "countryoforiginlandname": "Frankrike",
        "producer": "Esprit Calvados 5 domaines",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "42%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1015001",
        "articleid": "638546",
        "articletype": "10150",
        "name": "The Spice Tree",
        "name2": "",
        "priceinclvat": "499.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Whisky , Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Compass Box",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1015101",
        "articleid": "707630",
        "articletype": "10151",
        "name": "Grappa di Levi",
        "name2": "Levi Romano",
        "priceinclvat": "3446.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-12-01",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Levi Romano",
        "provider": "Haugen-Gruppen AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "50%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1015301",
        "articleid": "723096",
        "articletype": "10153",
        "name": "Highland Park",
        "name2": "Norse Gods Loki",
        "priceinclvat": "1399.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Skottland, Highlands, Islands, Orkney",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Highland Park",
        "provider": "Edrington Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "48.7%",
        "module": "T5",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1015601",
        "articleid": "828902",
        "articletype": "10156",
        "name": "Bocchino Riserva Cantina Privata",
        "name2": "18 Years",
        "priceinclvat": "749.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-05-02",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Grappa",
        "packaging": "Flaska",
        "captype": "Plastkork\/syntetkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Italien",
        "producer": "Distilleria Bocchino",
        "provider": "Brandpartners AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "45%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1015701",
        "articleid": "611207",
        "articletype": "10157",
        "name": "Lustau Brandy Solera",
        "name2": "Gran Reserva Finest Selection",
        "priceinclvat": "499.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-02-01",
        "finaldelivery": " ",
        "catgegory": "Brandy och Vinsprit, Brandy",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "Lustau",
        "provider": "Hjo Grosshandel AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1015902",
        "articleid": "854266",
        "articletype": "10159",
        "name": "Facile",
        "name2": "Arrak",
        "priceinclvat": "179.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-06-02",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013vrig sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Facile & Co",
        "provider": "Facile & Co AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016101",
        "articleid": "633586",
        "articletype": "10161",
        "name": "Benriach",
        "name2": "Liquid Sun 15 Years",
        "priceinclvat": "799.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-03-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Liquid Sun Whisky",
        "provider": "Symposion International AB",
        "productionyear": "1996",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016301",
        "articleid": "639227",
        "articletype": "10163",
        "name": "Littlemill",
        "name2": "Liquid Sun 22 Years",
        "priceinclvat": "1399.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-19",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Lowlands",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Ehrlich & Schneider Gbr.",
        "provider": "Symposion International AB",
        "productionyear": "1989",
        "testedproductionyear": "",
        "alcoholstrength": "52.2%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016501",
        "articleid": "639258",
        "articletype": "10165",
        "name": "Compass Box",
        "name2": "Hedonism",
        "priceinclvat": "725.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Whisky, Grain",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Compass Box",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "43%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016601",
        "articleid": "639416",
        "articletype": "10166",
        "name": "Eau-de-Vie de Prune",
        "name2": "",
        "priceinclvat": "549.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Sprit av frukt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Frankrike",
        "producer": "Etienne Brana",
        "provider": "Divine AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "42%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016701",
        "articleid": "639451",
        "articletype": "10167",
        "name": "Eau-de-Vie Poire William",
        "name2": "",
        "priceinclvat": "559.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Sprit av frukt",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Frankrike",
        "producer": "Etienne Brana",
        "provider": "Divine AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "44%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016801",
        "articleid": "645592",
        "articletype": "10168",
        "name": "Eau-de-Vie Framboise",
        "name2": "",
        "priceinclvat": "599.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Sprit av frukt",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Frankrike",
        "producer": "Etienne Brana",
        "provider": "Divine AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "45%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1016901",
        "articleid": "645598",
        "articletype": "10169",
        "name": "Eau-de-Vie Marc D'Iroul\u00c3\u00a9guy",
        "name2": "",
        "priceinclvat": "499.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Grappa och Marc, Marc",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Frankrike",
        "producer": "Etienne Brana",
        "provider": "Divine AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "44%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1017301",
        "articleid": "644726",
        "articletype": "10173",
        "name": "Good ol' Sailor",
        "name2": "Jungle",
        "priceinclvat": "229.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-06-01",
        "finaldelivery": " ",
        "catgegory": "Smaksatt sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Galatea Spirits AB",
        "provider": "Galatea Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "TST",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1017402",
        "articleid": "644813",
        "articletype": "10174",
        "name": "Haga Sommar-Snaps",
        "name2": "Proven\u00c3\u00a7al Basilika, Timjan & Rosmarin",
        "priceinclvat": "139.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-06-01",
        "finaldelivery": " ",
        "catgegory": "Kryddad sprit",
        "packaging": "Flaska",
        "captype": "Plastkork\/syntetkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Cariel Spirits",
        "provider": "Cariel Spirits AB",
        "productionyear": "2012",
        "testedproductionyear": "",
        "alcoholstrength": "38%",
        "module": "T2",
        "assortment": "TST",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1017801",
        "articleid": "647552",
        "articletype": "10178",
        "name": "Uno En Mil",
        "name2": "Solera Gran Reserva",
        "priceinclvat": "437.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-05-02",
        "finaldelivery": " ",
        "catgegory": "Brandy och Vinsprit, Brandy",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Jerez",
        "countryoforiginlandname": "Spanien",
        "producer": "Sanchez Romate",
        "provider": "Vi\u00c3\u00b1a Espa\u00c3\u00b1ola AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1017901",
        "articleid": "647558",
        "articletype": "10179",
        "name": "Cardenal Mendoza",
        "name2": "Carta Real Solera Gran Reserva",
        "priceinclvat": "671.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-05-02",
        "finaldelivery": " ",
        "catgegory": "Brandy och Vinsprit, Brandy",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "Jerez",
        "countryoforiginlandname": "Spanien",
        "producer": "Sanchez Romate",
        "provider": "Vi\u00c3\u00b1a Espa\u00c3\u00b1ola AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1018401",
        "articleid": "548413",
        "articletype": "10184",
        "name": "Ballechin",
        "name2": "#5 Marsala Matured",
        "priceinclvat": "899.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-02-21",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Edradour Distillery",
        "provider": "Galatea Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1018702",
        "articleid": "548418",
        "articletype": "10187",
        "name": "Braunstein 10:3",
        "name2": "",
        "priceinclvat": "999.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-02-21",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Danmark",
        "producer": "Bryghuset Braunstein",
        "provider": "Galatea Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1018801",
        "articleid": "548443",
        "articletype": "10188",
        "name": "The Whisky Agency",
        "name2": "Aultmore",
        "priceinclvat": "795.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-02-21",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland",
        "countryoforiginlandname": "Storbritannien",
        "producer": "The Whisky Agency",
        "provider": "Origo Wine Import",
        "productionyear": "1990",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1019202",
        "articleid": "817010",
        "articletype": "10192",
        "name": "Strane",
        "name2": "London Dry Gin",
        "priceinclvat": "401.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-04-01",
        "finaldelivery": " ",
        "catgegory": "Gin",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Sm\u00c3\u00b6gen Whisky AB",
        "provider": "Sm\u00c3\u00b6gen Whisky AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "47.4%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1068101",
        "articleid": "817833",
        "articletype": "10681",
        "name": "Kappa",
        "name2": "Pisco",
        "priceinclvat": "451.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2014-04-01",
        "finaldelivery": " ",
        "catgegory": "Brandy och Vinsprit, Vinsprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Chile",
        "producer": "Lapostolle",
        "provider": "Carovin AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "42.5%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1019301",
        "articleid": "611828",
        "articletype": "10193",
        "name": "Greenall's Berkeley Square",
        "name2": "",
        "priceinclvat": "499.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-03-01",
        "finaldelivery": " ",
        "catgegory": "Gin",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Storbritannien",
        "producer": "G & J Greenall",
        "provider": "Interbrands Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TST",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1019402",
        "articleid": "404133",
        "articletype": "10194",
        "name": "Rommehed",
        "name2": "Julakvavit",
        "priceinclvat": "192.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2009-11-16",
        "finaldelivery": " ",
        "catgegory": "Kryddad sprit",
        "packaging": "Flaska",
        "captype": "Plastkork\/syntetkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "",
        "provider": "Rommehed Wine & Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "TSS",
        "organic": "1",
        "kosher": "0"
    }, {
        "nr": "1019701",
        "articleid": "673516",
        "articletype": "10197",
        "name": "Danica Gin",
        "name2": "",
        "priceinclvat": "369.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-08-01",
        "finaldelivery": " ",
        "catgegory": "Gin",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "",
        "countryoforiginlandname": "Danmark",
        "producer": "Bryghuset Braunstein",
        "provider": "Galatea Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "44.7%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1019801",
        "articleid": "659727",
        "articletype": "10198",
        "name": "Caol Ila",
        "name2": "Distillers Edition",
        "priceinclvat": "579.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-09-01",
        "finaldelivery": " ",
        "catgegory": "Whisky , Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Islay",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Diageo Plc",
        "provider": "Diageo Sweden AB",
        "productionyear": "2012",
        "testedproductionyear": "",
        "alcoholstrength": "43%",
        "module": "T2",
        "assortment": "TST",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "102",
        "articleid": "2",
        "articletype": "1",
        "name": "Renat",
        "name2": "",
        "priceinclvat": "110.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "1993-10-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Internationellt m\u00c3\u00a4rke",
        "producer": "Pernod Ricard",
        "provider": "Pernod Ricard Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1020201",
        "articleid": "678323",
        "articletype": "10202",
        "name": "Longmorn",
        "name2": "MacKillop's Choice",
        "priceinclvat": "1280.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-09-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Angus Dundee",
        "provider": "Philipson S\u00c3\u00b6derberg AB",
        "productionyear": "1989",
        "testedproductionyear": "",
        "alcoholstrength": "43%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1020404",
        "articleid": "548667",
        "articletype": "10204",
        "name": "Collection 3",
        "name2": "Peated",
        "priceinclvat": "579.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-02-21",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013vrig sprit",
        "packaging": "3 fl \u00c3\u00a0 200 ml",
        "captype": "",
        "countryoforigin": "England",
        "countryoforiginlandname": "Storbritannien",
        "producer": "The English Whisky Co",
        "provider": "Clydesdale AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1021201",
        "articleid": "683591",
        "articletype": "10212",
        "name": "Royal Salute",
        "name2": "21 Years",
        "priceinclvat": "1295.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-09-01",
        "finaldelivery": " ",
        "catgegory": "Whisky , Blended",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Chivas Brother's",
        "provider": "Pernod Ricard Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1022301",
        "articleid": "405628",
        "articletype": "10223",
        "name": "Altissima",
        "name2": "Vulgaris",
        "priceinclvat": "398.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2009-11-16",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013vrig sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Tr\u00c3\u00a4kumla Rom",
        "provider": "Handpicked Wines Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1023601",
        "articleid": "422685",
        "articletype": "10236",
        "name": "Blanche de Montal",
        "name2": "",
        "priceinclvat": "395.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2010-02-15",
        "finaldelivery": " ",
        "catgegory": "Brandy och Vinsprit, Vinsprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Armagnac",
        "countryoforiginlandname": "Frankrike",
        "producer": "Armagnac Montal",
        "provider": "Symposion International AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "40%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1023901",
        "articleid": "195565",
        "articletype": "10239",
        "name": "Tanqueray",
        "name2": "London Dry Gin",
        "priceinclvat": "279.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2006-04-01",
        "finaldelivery": " ",
        "catgegory": "Gin",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Tanqueray Gordon",
        "provider": "Diageo Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "43.1%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1024601",
        "articleid": "560847",
        "articletype": "10246",
        "name": "The Whisky Agency",
        "name2": "Laphroaig",
        "priceinclvat": "725.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-03-15",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Islay",
        "countryoforiginlandname": "Storbritannien",
        "producer": "The Whisky Agency",
        "provider": "Origo Wine Import",
        "productionyear": "2000",
        "testedproductionyear": "",
        "alcoholstrength": "52.5%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1024702",
        "articleid": "560340",
        "articletype": "10247",
        "name": "Mortlach",
        "name2": "Cask 2310",
        "priceinclvat": "583.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-05-02",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Gordon & MacPhail",
        "provider": "Symposion International AB",
        "productionyear": "1984",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    }, {
        "nr": "1025001",
        "articleid": "678924",
        "articletype": "10250",
        "name": "Laphroaig",
        "name2": "MacKillop's Choice",
        "priceinclvat": "1950.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-09-01",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Islay",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Angus Dundee",
        "provider": "Philipson S\u00c3\u00b6derberg AB",
        "productionyear": "1990",
        "testedproductionyear": "",
        "alcoholstrength": "52.2%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },];
    container = document.getElementById('itemsContainer');
    for (i = 0; i < count.length; i++) {
        // the original string stored the content of each card, and default in english

        origin_string = `
        <div id = "${i}"class="col" ontouchstart="this.classList.toggle('hover');">
              <div class="container">
                <div class="front" style="background-image: url(./logo.png)">
                  <div class="inner">
                    <p> ${count[i].name} </p>
                    <span>${count[i].name2}</span>
                  </div>
                </div>
                <div class="back">
                  <div class="inner">
                    <p><span>Alc: ${count[i].alcoholstrength}</span>
                      <br/>
                      <span>Price:${count[i].priceinclvat} SEK</span>
                      </p>
                  </div>
                </div>
              </div>
            </div>
        
        `;
        // changing the content of the orginal string according to the language selector

        if (lang === 'en') {
            temp_string = origin_string.replace("Price", "Price");
        } else if (lang === 'sw') {
            temp_string = origin_string.replace("Price", "Pris");
        } else {
            temp_string = origin_string.replace("Price", "Preis");
        }
        // concatenating in the container

        container.innerHTML += temp_string;
    }

    // });
}
//loading the content page

window.addEventListener('DOMContentLoaded', display);
